# Generated by Django 4.2.6 on 2023-10-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_auth', '0004_customer_is_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
