# Generated by Django 4.2.6 on 2023-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_auth', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
