# Generated by Django 4.2.6 on 2023-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_category_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pics',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='categories/'),
        ),
    ]
