# Generated by Django 4.2.6 on 2023-10-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_remove_category_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
