# Generated by Django 4.2.6 on 2023-10-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_alter_brand_description_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='total_products',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_products',
        ),
    ]
