# Generated by Django 4.2.6 on 2023-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_remove_brand_total_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
