# Generated by Django 4.2.6 on 2023-11-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_is_active"),
        ("adminside", "0015_custom_user_country_custom_user_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offers.offer",
            ),
        ),
    ]
