# Generated by Django 4.2.6 on 2023-12-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_offer_discount"),
        ("adminside", "0017_custom_user_refferal_code_custom_user_refferer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offers.offer",
            ),
        ),
    ]
