# Generated by Django 4.2.6 on 2023-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("coupon_code", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("discount", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
