# Generated by Django 4.2.6 on 2023-11-25 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
