# Generated by Django 4.2.6 on 2023-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
