# Generated by Django 4.2.6 on 2023-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile',
            field=models.ImageField(blank=True, default='No images available', null=True, upload_to='profile/'),
        ),
    ]
