# Generated by Django 4.2.6 on 2023-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='mobile_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
