# Generated by Django 4.2.6 on 2023-11-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(blank=True, default=' ', null=True),
        ),
    ]
