# Generated by Django 4.2.6 on 2023-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='mobile_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
