# Generated by Django 4.2.6 on 2023-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0012_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="made_on",
            field=models.DateField(auto_now_add=True),
        ),
    ]
