# Generated by Django 4.2.6 on 2023-11-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0013_alter_wallet_made_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="made_on",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="note",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="transaction",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("transaction", models.CharField(max_length=50, null=True)),
                ("made_on", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.wallet",
                    ),
                ),
            ],
        ),
    ]
