# Generated by Django 4.2.6 on 2023-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0014_remove_wallet_made_on_remove_wallet_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
