# Generated by Django 4.2.6 on 2023-12-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0017_user_profile_refferal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="refferer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_profile.user_profile",
            ),
        ),
    ]
