# Generated by Django 4.2.6 on 2023-12-01 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0018_user_profile_refferer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_profile",
            name="refferal_code",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="refferer",
        ),
    ]
