# Generated by Django 4.2.6 on 2023-12-06 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0019_remove_user_profile_refferal_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
