# Generated by Django 4.2.6 on 2023-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_amount_paid_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
