# Generated by Django 4.2.6 on 2023-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_line_1_alter_order_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
