# Generated by Django 4.2.6 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(default='not available', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Deliverd', 'Deliverd'), ('Cancel', 'Cancel')], default='New', max_length=10),
        ),
    ]
