# Generated by Django 4.2.6 on 2023-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_phone2_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='district',
        ),
        migrations.AddField(
            model_name='order',
            name='hometown',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
