# Generated by Django 4.2.6 on 2023-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="status",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
