# Generated by Django 4.2.6 on 2023-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_cancelorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
