# Generated by Django 4.2.6 on 2023-11-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_onlinepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinepayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="payment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
