# Generated by Django 4.2.6 on 2023-11-25 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_coupons_couponusage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponusage",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="couponusage",
            name="user",
        ),
        migrations.DeleteModel(
            name="Coupons",
        ),
        migrations.DeleteModel(
            name="CouponUsage",
        ),
    ]
