# Generated by Django 4.2.6 on 2023-11-25 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_coupons_couponusage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="couponusage",
            old_name="disount_amount",
            new_name="discount_amount",
        ),
    ]
