# Generated by Django 4.2.6 on 2023-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_rename_disount_amount_couponusage_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponusage",
            name="discount_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="total_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
