# Generated by Django 4.2.6 on 2023-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_coupons_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponusage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
