# Generated by Django 4.2.6 on 2023-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0020_orderreturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreturn",
            name="collected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Deliverd", "Deliverd"),
                    ("Cancel", "Cancel"),
                    ("Return", "Return"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
