# Generated by Django 4.2.6 on 2023-11-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0021_orderreturn_collected_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreturn",
            name="amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
