# Generated by Django 4.2.6 on 2023-10-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0009_remove_category_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('subcategory', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('sizes', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(default='NA', max_length=50)),
                ('return_time', models.CharField(default='Return not available', max_length=50)),
                ('meterial', models.CharField(default='NA', max_length=50)),
                ('warranty', models.CharField(default='NA', max_length=50)),
                ('image', models.ImageField(blank=True, default='No images available', upload_to='products/')),
                ('special', models.BooleanField(default=False)),
                ('offer_pro', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='No images available', upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
