# Generated by Django 4.2.6 on 2023-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
