# Generated by Django 4.2.6 on 2023-10-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_brand'),
        ('products', '0002_products_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminside.brand'),
            preserve_default=False,
        ),
    ]
