# Generated by Django 4.2.6 on 2023-10-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_weight_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
