# Generated by Django 4.2.6 on 2023-11-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_is_active"),
        ("products", "0010_alter_products_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offers.offer",
            ),
        ),
    ]
