# Generated by Django 4.2.6 on 2023-12-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_offer_discount"),
        ("products", "0012_alter_products_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offers.offer",
            ),
        ),
    ]
